(function (G) {
  'use strict';

  var QUESTS = [
    {
      id:'q_slime_hunt',
      title:'史萊姆剋星',
      npc:'chief',
      type:'kill',
      target:'slime',
      targetName:'史萊姆',
      goal:10,
      desc:'幫我消滅村子附近的史萊姆，牠們讓農田沒辦法耕種！',
      rewardGold:100,
      rewardExp:80,
      rewardItems:[{id:'health_potion', qty:3}],
      next:'q_wolf_threat',
    },
    {
      id:'q_wolf_threat',
      title:'狼群威脅',
      npc:'chief',
      type:'kill',
      target:'wolf',
      targetName:'野狼',
      goal:5,
      desc:'北方森林的野狼最近在搶奪牲畜，請你清除牠們！',
      rewardGold:200,
      rewardExp:150,
      rewardItems:[{id:'iron_sword', qty:1}],
      next:'q_gather_herbs',
    },
    {
      id:'q_gather_herbs',
      title:'採集草藥',
      npc:'alchemist',
      type:'collect',
      target:'herb',
      targetName:'草藥',
      goal:8,
      desc:'我的庫存快見底了，能幫我採集 8 株草藥嗎？',
      rewardGold:60,
      rewardExp:60,
      rewardItems:[{id:'mp_potion', qty:5}],
      next:'q_iron_supply',
    },
    {
      id:'q_iron_supply',
      title:'鐵礦供應',
      npc:'blacksmith',
      type:'collect',
      target:'iron_ore',
      targetName:'鐵礦石',
      goal:15,
      desc:'鍛造材料不夠用了！去採些鐵礦石回來，我付你好價錢。',
      rewardGold:150,
      rewardExp:100,
      rewardItems:[{id:'iron_chest', qty:1}],
      next:'q_boar_menace',
    },
    {
      id:'q_boar_menace',
      title:'野豬之禍',
      npc:'chief',
      type:'kill',
      target:'boar',
      targetName:'野豬',
      goal:8,
      desc:'草原上的野豬成群，已經傷到好幾個村民了！',
      rewardGold:300,
      rewardExp:200,
      rewardItems:[{id:'hi_potion', qty:2}, {id:'steel_ingot', qty:3}],
      next:'q_ice_crystal',
    },
    {
      id:'q_ice_crystal',
      title:'冰晶研究',
      npc:'alchemist',
      type:'collect',
      target:'ice_shard',
      targetName:'冰晶碎片',
      goal:10,
      desc:'雪地裡的冰元素帶著珍貴的冰晶，我需要它們來研究新藥方！',
      rewardGold:400,
      rewardExp:250,
      rewardItems:[{id:'mage_pendant', qty:1}],
      next:'q_fire_boss',
    },
    {
      id:'q_fire_boss',
      title:'討伐熔岩惡魔',
      npc:'chief',
      type:'kill',
      target:'lavaDemon',
      targetName:'熔岩魔',
      goal:3,
      desc:'火山地帶的熔岩惡魔越來越危險，必須消滅牠們！',
      rewardGold:800,
      rewardExp:500,
      rewardItems:[{id:'elixir', qty:1}, {id:'flame_blade', qty:1}],
      next:null,
    },
    {
      id:'q_void_essence',
      title:'虛空研究',
      npc:'alchemist',
      type:'collect',
      target:'void_essence',
      targetName:'虛空精華',
      goal:5,
      desc:'深淵的虛空精留下的精華是最難得的煉金材料……危險，但值得！',
      rewardGold:1000,
      rewardExp:600,
      rewardItems:[{id:'elixir', qty:2}, {id:'elder_staff', qty:1}],
      next:null,
    },
  ];

  G.QuestDatabase = {
    get:    function (id) { return QUESTS.find(function (q) { return q.id === id; }) || null; },
    all:    function ()   { return QUESTS; },
    getFor: function (npcId) { return QUESTS.filter(function (q) { return q.npc === npcId; }); },
  };
})(window.Game = window.Game || {});
